### ISSUE TITLE
PathPlanner Improvement

### ISSUE THREAD

**Issue by JosephTLockwood** [Hemlock5712/2025SwerveTemplate#12]
A couple of small improvements for PathPlanner
- [ ] Add PathPlanner Warmups (in Robot.java)
- [ ] Add import from GUI if possible (otherwise default to hardcoded)

**Comment by AydenLo17** [comment]
Add this to lines 58-67 of Robot.java

`
  @Override
  public void robotInit() {

    // Warmup the PPLib library
    FollowPathCommand.warmupCommand().schedule();
    PathfindingCommand.warmupCommand().schedule();

    RobotController.setBrownoutVoltage(6.5);
  }`

**Comment by AydenLo17** [comment]
Unsure about _import from GUI_ but this will solve the _Warmup_ improvement
